### ISSUE TITLE
Cannot Use SIDH-RS Due To Subtle Dependency

### ISSUE THREAD

**Issue by AtropineTears** [etairi/sidh-rs#2]
Hello,

I cannot use SIDH-RS due to the subtle dependecy being `^0.3`. The closest version found was `2.4.1`. Could you update SIDH using subtle `2.4.1` or find a way to fix this error. Error Message Below:

```
failed to select a version for the requirement `subtle = "^0.3"`
candidate versions found which didn't match: 2.4.1, 2.4.0, 2.3.0, ...
location searched: crates.io index
required by package `sidh v0.2.0`
```

Thank you.

**Comment by etairi** [comment]
@AtropineTears Can you please try again? I updated the packages.

**Comment by AtropineTears** [comment]
Can you upload it to crates.io?

**Comment by etairi** [comment]
@AtropineTears I just uploaded. Let me know once you try.

**Comment by AtropineTears** [comment]
Hi, it works now. Thank you!
