### ISSUE TITLE
Running on ARM64, etc.?

### ISSUE THREAD

**Issue by adamierymenko** [etairi/sidh-rs#3]
The x86 (not x64) code seems to be plain vanilla Rust. Is there any reason this can't be used on any architecture? If not why isn't it `#[cfg(not(target_arch = "x86_64"))]` instead of x86 only? It might be less efficient than a native implementation on 64-bit platforms but it would work wouldn't it?

**Comment by etairi** [comment]
@adamierymenko Yes, it should work I believe. The primary reason as you mentioned was efficiency.
